# Generated by Django 4.2.6 on 2023-11-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('C_account', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='账号')),
                ('C_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('C_sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=5, verbose_name='性别')),
                ('C_birth', models.DateField(max_length=20, verbose_name='出生日期')),
                ('C_phone', models.CharField(max_length=11, unique=True, verbose_name='电话')),
                ('C_ordernum', models.CharField(default=0, max_length=10, verbose_name='完成订单数')),
            ],
        ),
        migrations.CreateModel(
            name='FoodTable',
            fields=[
                ('Ft_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='餐桌号')),
                ('Ft_number', models.IntegerField(verbose_name='座位数')),
                ('Ft_state', models.CharField(choices=[('使用中', '使用中'), ('待清洁', '待清洁'), ('空闲', '空闲')], default='空闲', max_length=10, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('M_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='菜品编号')),
                ('M_name', models.CharField(max_length=10, unique=True, verbose_name='菜名')),
                ('M_class', models.CharField(max_length=10, verbose_name='类别')),
                ('M_price', models.IntegerField(verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='账号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('authority', models.CharField(choices=[('1', '副店长'), ('0', '店长'), ('2', '管理员')], default='1', max_length=5, verbose_name='身份')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('W_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='工号')),
                ('W_name', models.CharField(max_length=10, verbose_name='姓名')),
                ('W_sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=5, verbose_name='性别')),
                ('W_birth', models.DateField(max_length=20, verbose_name='出生日期')),
                ('W_job', models.CharField(choices=[('服务员', '服务员'), ('厨师', '厨师'), ('保洁', '保洁')], max_length=10, verbose_name='职务')),
                ('W_phone', models.CharField(max_length=11, unique=True, verbose_name='电话')),
                ('W_salary', models.IntegerField(verbose_name='工资')),
                ('W_addr', models.CharField(max_length=30, verbose_name='家庭住址')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('O_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='订单号')),
                ('O_time', models.DateTimeField(max_length=20, verbose_name='消费时间')),
                ('O_cost', models.IntegerField(verbose_name='消费金额')),
                ('O_state', models.CharField(choices=[('未支付', '未支付'), ('已支付', '已支付')], default='未支付', max_length=10, verbose_name='订单状态')),
                ('C_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSite.customer', verbose_name='顾客账号')),
                ('Ft_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSite.foodtable', verbose_name='餐桌号')),
                ('W_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appSite.worker', verbose_name='服务员工号')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('M_num', models.IntegerField(verbose_name='菜品数量')),
                ('M_cost', models.IntegerField(default=0, verbose_name='总价格')),
                ('M_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_orders_by_id', to='appSite.menu', verbose_name='菜品编号')),
                ('M_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_orders_by_name', to='appSite.menu', to_field='M_name', verbose_name='菜品')),
                ('O_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSite.order', verbose_name='订单号')),
            ],
        ),
    ]
