# Generated by Django 4.2.6 on 2023-11-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_order',
            name='M_name',
        ),
    ]
