# Generated by Django 4.2.6 on 2023-11-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSite', '0002_remove_menu_order_m_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='C_ordernum',
            field=models.IntegerField(default=0, max_length=10, verbose_name='完成订单数'),
        ),
    ]
