# Generated by Django 4.2.6 on 2023-11-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSite', '0003_alter_customer_c_ordernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='C_ordernum',
            field=models.IntegerField(default=0, verbose_name='完成订单数'),
        ),
    ]
